STEP 2. Loading datasets...
<torch.utils.data.dataloader.DataLoader object at 0x7f8fa697a190>
Loaded 1000 test files
STEP 3. Loading model and metrics...
Loaded model enet2021 for decnet-completion
STEP 4. Training or eval stage...
Currently on image 0 out of 1000
torch_min_max (0.0, 1.0, 0.4223612844944, 0.3294117748737335)
pred_torch_min_max (1.4638134241104126, 14.198532104492188, 5.971986770629883, 5.256314277648926)
Mean values per iter: {'d1': 0.16039875149726868, 'd2': 0.34952282905578613, 'd3': 0.5551828742027283, 'abs_rel': 0.5493959784507751, 'sq_rel': 6.406434535980225, 'rmse': 12.81212043762207, 'rmse_log': 1.0194469690322876, 'log10': 0.33929988741874695, 'silog': 0.959858238697052}
/home/dim/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/functional.py:3635: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/home/dim/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/functional.py:3680: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  "The default behavior for interpolate/upsample with float scale_factor changed "
Traceback (most recent call last):
  File "main.py", line 159, in <module>
    visualizer.plotter(pred_d,sparse_depth,depth_gt,pred,data['rgb'])
  File "/home/dim/depth_2022/visualizers/visualizer.py", line 187, in plotter
    plt.show()
  File "/home/dim/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 368, in show
    return _backend_mod.show(*args, **kwargs)
  File "/home/dim/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3524, in show
    cls.mainloop()
  File "/home/dim/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/matplotlib/backends/backend_qt.py", line 1014, in mainloop
    qt_compat._exec(qApp)
  File "/home/dim/anaconda3/envs/pytorchenv/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/dim/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/matplotlib/backends/qt_compat.py", line 262, in _maybe_allow_interrupt
    old_sigint_handler(*handler_args)
KeyboardInterrupt